#!/bin/sh

function generate_project_tree() {
  # Original from https://stackoverflow.com/a/35889620/11929317
  # This is a ported version for mac
  IGNORED="venv|update-readme|new-boj|README.md"
  SED_FOR_MAC="gsed"

  if [[ "$OSTYPE" == "darwin"* ]]; then
    if command -v $SED_FOR_MAC >/dev/null; then
      SED=$SED_FOR_MAC
    else
      echo "$SED_FOR_MAC not installed!" && exit 1
    fi
  else
    SED="sed"
  fi

  tree -tf --noreport -I '*~' --charset ascii $1 | 
    $SED -e '1d' | 
    $SED -e 's/| \+/  /g' | 
    $SED -e 's/[|`]-\+/ */g' |
    $SED -e 's:\(* \)\(\(.*/\)\([^/]\+\)\):\1[\4](\2):g' 
}

function generate_readme() {
  readme="$1/README.md"
  readme_template="$1/.readme_template.md"

  # perl -p0e "s/=PROJECT_TREE=/$(generate_project_tree .)/se" "$readme_template" > "$readme"
}

cd "$(dirname "$0")" || exit 1
generate_project_tree . | generate_readme .